version: "3.8"
services:
  app:
    build: .
    ports:
      - "4281:8080"
      - "4282:8443"
    environment:
      - DATABASE_URL=jdbc:sqlite:/app-data/db/simple-split.sqlite?journal_mode=WAL&busy_timeout=30000
    volumes:
      - ss-app-data:/app-data

volumes:
  ss-app-data:
    driver: local
