/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurrencyDto {
    #[serde(rename = "isoCode")]
    pub iso_code: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "symbol")]
    pub symbol: String,
}

impl CurrencyDto {
    pub fn new(iso_code: String, name: String, symbol: String) -> CurrencyDto {
        CurrencyDto {
            iso_code,
            name,
            symbol,
        }
    }
}
