/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorMessageDto {
    #[serde(
        rename = "message",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub message: Option<Option<String>>,
    #[serde(rename = "exception")]
    pub exception: String,
    #[serde(rename = "stacktraceBase64")]
    pub stacktrace_base64: String,
    #[serde(rename = "stacktraceLines")]
    pub stacktrace_lines: Vec<String>,
}

impl ErrorMessageDto {
    pub fn new(
        exception: String,
        stacktrace_base64: String,
        stacktrace_lines: Vec<String>,
    ) -> ErrorMessageDto {
        ErrorMessageDto {
            message: None,
            exception,
            stacktrace_base64,
            stacktrace_lines,
        }
    }
}
