/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExpenseDto {
    #[serde(rename = "splitBetween")]
    pub split_between: Vec<models::MemberDto>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "modified")]
    pub modified: models::TimestampDto,
    #[serde(rename = "paidBy")]
    pub paid_by: Vec<models::MemberDto>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "created")]
    pub created: models::TimestampDto,
    #[serde(rename = "currency")]
    pub currency: models::CurrencyDto,
    #[serde(rename = "uid")]
    pub uid: String,
}

impl ExpenseDto {
    pub fn new(
        split_between: Vec<models::MemberDto>,
        description: String,
        amount: f64,
        modified: models::TimestampDto,
        paid_by: Vec<models::MemberDto>,
        title: String,
        created: models::TimestampDto,
        currency: models::CurrencyDto,
        uid: String,
    ) -> ExpenseDto {
        ExpenseDto {
            split_between,
            description,
            amount,
            modified,
            paid_by,
            title,
            created,
            currency,
            uid,
        }
    }
}
