/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGroupsResponse {
    #[serde(rename = "groups")]
    pub groups: Vec<models::GroupDto>,
    #[serde(rename = "errors", default)]
    pub errors: Vec<models::GetGroupErrorDto>,
}

impl GetGroupsResponse {
    pub fn new(
        groups: Vec<models::GroupDto>,
        errors: Vec<models::GetGroupErrorDto>,
    ) -> GetGroupsResponse {
        GetGroupsResponse { groups, errors }
    }
}

#[cfg(test)]
mod tests {
    use super::GetGroupsResponse;

    #[test]
    fn omitted_errors_are_deserialized_as_an_empty_list() {
        let response: GetGroupsResponse =
            serde_json::from_str(r#"{"groups":[]}"#).expect("response should deserialize");

        assert!(response.groups.is_empty());
        assert!(response.errors.is_empty());
    }
}
