/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetGroupsResponse {
    #[serde(rename = "groups")]
    pub groups: Vec<models::GroupDto>,
    #[serde(rename = "errors")]
    pub errors: Vec<models::GetGroupErrorDto>,
}

impl GetGroupsResponse {
    pub fn new(
        groups: Vec<models::GroupDto>,
        errors: Vec<models::GetGroupErrorDto>,
    ) -> GetGroupsResponse {
        GetGroupsResponse { groups, errors }
    }
}
