/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCurrenciesResponse {
    #[serde(rename = "currencies")]
    pub currencies: Vec<models::CurrencyDto>,
}

impl GetCurrenciesResponse {
    pub fn new(currencies: Vec<models::CurrencyDto>) -> GetCurrenciesResponse {
        GetCurrenciesResponse { currencies }
    }
}
