/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupDto {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "paybackTransactions", default)]
    pub payback_transactions: Vec<models::TransactionDto>,
    #[serde(rename = "modified")]
    pub modified: models::TimestampDto,
    #[serde(rename = "members", default)]
    pub members: Vec<models::MemberDto>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "expenses", default)]
    pub expenses: Vec<models::ExpenseDto>,
    #[serde(rename = "created")]
    pub created: models::TimestampDto,
    #[serde(rename = "currency")]
    pub currency: models::CurrencyDto,
    #[serde(rename = "uid")]
    pub uid: String,
}

impl GroupDto {
    pub fn new(
        description: String,
        payback_transactions: Vec<models::TransactionDto>,
        modified: models::TimestampDto,
        members: Vec<models::MemberDto>,
        title: String,
        expenses: Vec<models::ExpenseDto>,
        created: models::TimestampDto,
        currency: models::CurrencyDto,
        uid: String,
    ) -> GroupDto {
        GroupDto {
            description,
            payback_transactions,
            modified,
            members,
            title,
            expenses,
            created,
            currency,
            uid,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::GroupDto;

    #[test]
    fn omitted_empty_collections_are_deserialized_as_empty_lists() {
        let json = r#"{
            "description": "A new group",
            "modified": {"timestampSeconds": 0, "formatted": ""},
            "title": "New group",
            "created": {"timestampSeconds": 0, "formatted": ""},
            "currency": {"isoCode": "EUR", "name": "Euro", "symbol": "€"},
            "uid": "group-id"
        }"#;

        let group: GroupDto = serde_json::from_str(json).expect("group should deserialize");

        assert!(group.payback_transactions.is_empty());
        assert!(group.members.is_empty());
        assert!(group.expenses.is_empty());
    }
}
