/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupDto {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "paybackTransactions")]
    pub payback_transactions: Vec<models::TransactionDto>,
    #[serde(rename = "modified")]
    pub modified: models::TimestampDto,
    #[serde(rename = "members")]
    pub members: Vec<models::MemberDto>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "expenses")]
    pub expenses: Vec<models::ExpenseDto>,
    #[serde(rename = "created")]
    pub created: models::TimestampDto,
    #[serde(rename = "currency")]
    pub currency: models::CurrencyDto,
    #[serde(rename = "uid")]
    pub uid: String,
}

impl GroupDto {
    pub fn new(
        description: String,
        payback_transactions: Vec<models::TransactionDto>,
        modified: models::TimestampDto,
        members: Vec<models::MemberDto>,
        title: String,
        expenses: Vec<models::ExpenseDto>,
        created: models::TimestampDto,
        currency: models::CurrencyDto,
        uid: String,
    ) -> GroupDto {
        GroupDto {
            description,
            payback_transactions,
            modified,
            members,
            title,
            expenses,
            created,
            currency,
            uid,
        }
    }
}
