/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemberDto {
    #[serde(rename = "uid")]
    pub uid: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl MemberDto {
    pub fn new(uid: String, name: String) -> MemberDto {
        MemberDto { uid, name }
    }
}
