/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewExpenseDto {
    #[serde(rename = "splitBetween")]
    pub split_between: Vec<models::UserNameDto>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(
        rename = "isSplitBetweenAll",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_split_between_all: Option<Option<bool>>,
    #[serde(rename = "paidBy")]
    pub paid_by: Vec<models::UserNameDto>,
    #[serde(rename = "title")]
    pub title: String,
}

impl NewExpenseDto {
    pub fn new(
        split_between: Vec<models::UserNameDto>,
        description: String,
        amount: f64,
        paid_by: Vec<models::UserNameDto>,
        title: String,
    ) -> NewExpenseDto {
        NewExpenseDto {
            split_between,
            description,
            amount,
            is_split_between_all: None,
            paid_by,
            title,
        }
    }
}
