/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostGroupRequest {
    #[serde(rename = "currencyIsoCode")]
    pub currency_iso_code: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "members")]
    pub members: Vec<models::UserNameDto>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "expenses")]
    pub expenses: Vec<models::NewExpenseDto>,
    #[serde(rename = "password")]
    pub password: String,
}

impl PostGroupRequest {
    pub fn new(
        currency_iso_code: String,
        description: String,
        members: Vec<models::UserNameDto>,
        title: String,
        expenses: Vec<models::NewExpenseDto>,
        password: String,
    ) -> PostGroupRequest {
        PostGroupRequest {
            currency_iso_code,
            description,
            members,
            title,
            expenses,
            password,
        }
    }
}
