/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostMemberRequest {
    #[serde(rename = "groupUid")]
    pub group_uid: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl PostMemberRequest {
    pub fn new(group_uid: String, name: String) -> PostMemberRequest {
        PostMemberRequest { group_uid, name }
    }
}
