/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostMemberResponse {
    #[serde(rename = "group")]
    pub group: models::GroupDto,
}

impl PostMemberResponse {
    pub fn new(group: models::GroupDto) -> PostMemberResponse {
        PostMemberResponse { group }
    }
}
