/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostExpenseResponse {
    #[serde(rename = "expense")]
    pub expense: models::ExpenseDto,
}

impl PostExpenseResponse {
    pub fn new(expense: models::ExpenseDto) -> PostExpenseResponse {
        PostExpenseResponse { expense }
    }
}
