/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutGroupRequest {
    /// If not set, this field defaults to the value of the default annotation.
    #[serde(
        rename = "currencyIsoCode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub currency_iso_code: Option<Option<String>>,
    /// If not set, this field defaults to the value of the default annotation.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// If not set, this field defaults to the value of the default annotation.
    #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
    pub members: Option<Vec<models::UserUidDto>>,
    /// If not set, this field defaults to the value of the default annotation.
    #[serde(
        rename = "title",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub title: Option<Option<String>>,
    /// If not set, this field defaults to the value of the default annotation.
    #[serde(
        rename = "password",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub password: Option<Option<String>>,
}

impl PutGroupRequest {
    pub fn new() -> PutGroupRequest {
        PutGroupRequest {
            currency_iso_code: None,
            description: None,
            members: None,
            title: None,
            password: None,
        }
    }
}
