/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutExpenseRequest {
    /// If not set, this field defaults to the value of the default annotation.
    #[serde(rename = "splitBetween", skip_serializing_if = "Option::is_none")]
    pub split_between: Option<Vec<models::UserUidDto>>,
    /// If not set, this field defaults to the value of the default annotation.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// If not set, this field defaults to the value of the default annotation.
    #[serde(
        rename = "amount",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub amount: Option<Option<f64>>,
    /// If not set, this field defaults to the value of the default annotation.
    #[serde(
        rename = "isSplitBetweenAll",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub is_split_between_all: Option<Option<bool>>,
    /// If not set, this field defaults to the value of the default annotation.
    #[serde(rename = "paidBy", skip_serializing_if = "Option::is_none")]
    pub paid_by: Option<Vec<models::UserUidDto>>,
    /// If not set, this field defaults to the value of the default annotation.
    #[serde(
        rename = "title",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub title: Option<Option<String>>,
}

impl PutExpenseRequest {
    pub fn new() -> PutExpenseRequest {
        PutExpenseRequest {
            split_between: None,
            description: None,
            amount: None,
            is_split_between_all: None,
            paid_by: None,
            title: None,
        }
    }
}
