/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimestampDto {
    #[serde(rename = "timestampSeconds")]
    pub timestamp_seconds: i64,
    #[serde(rename = "formatted")]
    pub formatted: String,
}

impl TimestampDto {
    pub fn new(timestamp_seconds: i64, formatted: String) -> TimestampDto {
        TimestampDto {
            timestamp_seconds,
            formatted,
        }
    }
}
