/*
 * Simple Split API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionDto {
    #[serde(rename = "creditorUid")]
    pub creditor_uid: String,
    #[serde(rename = "debtorUid")]
    pub debtor_uid: String,
    #[serde(rename = "amount")]
    pub amount: f64,
}

impl TransactionDto {
    pub fn new(creditor_uid: String, debtor_uid: String, amount: f64) -> TransactionDto {
        TransactionDto {
            creditor_uid,
            debtor_uid,
            amount,
        }
    }
}
