name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-kotlin-code-format:
    name: Check Kotlin code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download ktlint binary
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.2.1/ktlint
          chmod +x ktlint
          cp ktlint android/ktlint

      - name: Run ktlint
        run: cd android && ./ktlint --editorconfig=".editorconfig"

  build-android-app:
    name: Build Android app
    needs: [ check-kotlin-code-format ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup version variable
        run: |
          echo "VERSION=$(grep 'appVersion' ./android/gradle/libs.versions.toml | cut -d= -f2 | cut -d'"' -f2)" >> $GITHUB_ENV

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build debug apk
        run: cd android && ./gradlew app:assembleDebug

      - name: Store APK file
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: ./android/app/build/outputs/apk/debug/app-debug.apk

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Cache Dependencies
        uses: coursier/cache-action@v6

      - name: Run sbt compile
        run: cd backend && sbt app/compile

      - name: Run tests
        run: cd backend && sbt app/test

      - name: Build jar file
        run: cd backend && sbt app/assembly

      - name: Store jar file
        uses: actions/upload-artifact@v4
        with:
          name: simple-split-backend.jar
          path: ./backend/app/target/scala-3.7.1/simple-split-backend.jar

  transpile-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Cache Dependencies
        uses: coursier/cache-action@v6

      - name: Run transpiler
        run: |
          rm -r android/backend-api/src/main/kotlin/com
          cd backend && sbt codegen/generateKotlinClasses

      - name: Compile transpiled API
        run: cd android && ./gradlew backend-api:assemble
