name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Cache Dependencies
        uses: coursier/cache-action@v6

      - name: Change project dir
        run: cd backend

      - name: Run sbt compile
        run: sbt app/compile

      - name: Run tests
        run: sbt app/test

      - name: Build jar file
        run: sbt app/assembly
