name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Cache Dependencies
        uses: coursier/cache-action@v6

      - name: Run sbt compile
        run: cd backend && sbt app/compile

      - name: Run tests
        run: cd backend && sbt app/test

      - name: Build jar file
        run: cd backend && sbt app/assembly

      - name: Store jar file
        uses: actions/upload-artifact@v4
        with:
          name: simple-split-backend.jar
          path: ./backend/app/target/scala-3.7.1/simple-split-backend.jar

  transpile-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Cache Dependencies
        uses: coursier/cache-action@v6

      - name: Run transpiler
        run: |
          rm -r android/backend-api/src/main/kotlin/com
          cd backend && sbt codegen/generateKotlinClasses

      - name: Compile transpiled API
        run: cd android && ./gradlew backend-api:assemble
