name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache sbt
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: sbt-${{ runner.os }}-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/**') }}
          restore-keys: |
            sbt-${{ runner.os }}-

      - name: Run sbt compile
        run: sbt compile

      - name: Run tests
        run: sbt test

      - name: Build jar file
        run: sbt assembly